version: "3.3"
services:

  ## Banco de dados ##
  database:
    image: "postgres-image:latest"
    container_name: database
    build:
      context: ./docker
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/docker/volumes/pgdata/_data
    environment:
      - POSTGRES_USER=easyvestadmin
      - POSTGRES_PASSWORD=easyvestadmin
      - POSTGRES_DB=easyvest
    restart: always

  ## Aplicacao do backend ##
  easyvest-backend:
    image: "easyvestbackend-image:latest"
    container_name: "easyvest-backend"
    build:
      context: ./
      dockerfile: Dockerfile.backend
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/easyvest
      - SPRING_DATASOURCE_USERNAME=easyvestadmin
      - SPRING_DATASOURCE_PASSWORD=easyvestadmin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  ## Front end ##
  ## Comente esse trecho abaixo para ter apenas o backend e o banco de dados ##
  # easyvest-frontend:
  #   image: "easyvestfrontend-image:latest"
  #   container_name: "easyvest-frontend"
  #   working_dir: /app
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.frontend
  #   depends_on:
  #     - easyvest-backend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - /app/node_modules
  #     - frontenddata:/app
  ############################################################################

volumes:
  pgdata:
  # frontenddata: