version: "3.3"
services:
  easyvest-backend:
    image: "easyvestbackend-image:latest"
    container_name: "easyvest-backend"
    build:
      context: docker
      dockerfile: Dockerfile.bakend
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/easyvest
      - SPRING_DATASOURCE_USERNAME=easyvestadmin
      - SPRING_DATASOURCE_PASSWORD=easyvestadmin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  database:
    image: "postgres-image:latest"
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/docker/volumes/pgdata/_data
    environment:
      - POSTGRES_USER=easyvestadmin
      - POSTGRES_PASSWORD=easyvestadmin
      - POSTGRES_DB=easyvest
    restart: always

volumes:
  pgdata: