#!/bin/bash

echo -e "+=+=+=+=+=+=+ UPDATING DATABASE IMAGE .... +=+=+=+=+=+=+\n"
# update database image
cd docker/
docker build -t postgres-image -f Dockerfile.db .

echo -e "\nDATABASE IMAGE HAS BEEN UPDATED!!!\n"

echo -e "+=+=+=+ UPDATING BACKEND APPLICATION IMAGE .... +=+=+=+\n"
# update backend image
cd ..
mvn clean package
docker build -t easyvestbackend-image -f Dockerfile.backend .

echo -e "\nBACKEND APPLICATION IMAGE HAS BEEN UPDATED!!!\n"
echo "UPDATE DOCKER FINISHED :)"
